project/config/routes.rb
Project::Application.routes.draw do
  get "o_users/new"
    resources :courses do
        resources :assignments
    end
    root :to => "static#welcome" #controller#action
    get 'auth/facebook/callback' => 'sessions#create'
    get 'auth/logout' => 'sessions#destroy',  :as => 'logout'
    get 'auth/failure' => 'sessions#failure'
    get 'home' => 'static#home'
    post 'home' => 'static#home'
    get 'about' => 'static#about'
    post 'validate' => "o_users#validate", :as => "validate"
    get 'signup' => "o_users#signup"
=begin
    get 'done/:id' => "assignments#done", :as => 'done'
    get 'late/:id' => "assignments#late", :as=> 'late'
    get 'past/:id,', to: 'assignments#past', as:'past'
=end
    resources :o_users
end

project/app/models/assignment.rb
class Assignment < ActiveRecord::Base
    attr_accessible :dueDate
    attr_accessible :name
    attr_accessible :priority
    attr_accessible :description
    attr_accessible :className
    attr_accessible :status
    attr_accessible :course_id
    attr_accessible :user_id

    belongs_to :course
end

project/app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :name
  attr_accessible :priority
  attr_accessible :user_id

  belongs_to :user
  has_many :assignments
end

project/app/models/o_user.rb
class OUser < ActiveRecord::Base
    attr_accessible :name
    attr_accessible :email
    attr_accessible :password
end

project/app/models/user.rb
class User < ActiveRecord::Base
    #attr_protected :uid, :provider, :name
    has_many :courses
    def self.create_with_omniauth(auth)
        #get the provider and uid key from auth and query the database, and if not there initializes a new user
        #tap returns the new user
        where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
              user.provider = auth.provider
              user.uid = auth.uid
              user.name = auth.info.name
              user.save!
         end
    end
end

project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user #requires that a user is logged in for an action to be run
    protected #prevents method from being invoked by a route

  def set_current_user #checks to see if logged in THIS DOESN'T WORK SO FAR
    @current_user = OUser.find_by_id(session[:user_id])
    @date = Date.today.strftime("%B %d, %Y")
    if @current_user == nil
        redirect_to root_path
    end
  end
end

project/app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  def create
    @course = Course.find_by_id(params[:course_id])
    params[:assignment][:className] = @course.name #for querying an assignment for a particular class
    params[:assignment][:course_id] = @course.id
    params[:assignment][:status] = "toDo"
    params[:assignment][:user_id] = @current_user.id
    if params[:assignment].values.include?("") #check if there are empty fields
      flash[:warning] = "Please fill in all fields"
      redirect_to :back
    else
      @assignment = Assignment.create!(params[:assignment])
      redirect_to course_path(params[:course_id])
    end
  end

  def new
  end

  def edit
    @assignment = Assignment.find(params[:id])
  end
  def destroy
    #raise
    @assignment = Assignment.find_by_id(params[:id])
    @assignment.destroy
    redirect_to :back
  end
  def show
    @assignment = Assignment.find_by_id(params[:id])
    @week = Date.today.at_beginning_of_week.strftime("%B %d, %Y")
    @endWeek = Date.today.at_beginning_of_week.advance(:days => 6)
  end
  def update
    @assignment = Assignment.find(params[:id])
    @assignment.update_attributes!(params[:assignment])
    redirect_to course_path(:id => params[:course_id])
  end

  def done
     @assignment = Assignment.find_by_id(params[:id])
    @assignment.update_attributes!(:status => "done")
    redirect_to :back
  end
end

project/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
    redirect_to home_path
  end

  def show
    @course = Course.find_by_id(params[:id])
    @id = params[:id]
    @assignments = Assignment.find(:all, :conditions =>{:course_id => params[:id], :user_id => @current_user.id})
    @week = Date.today.at_beginning_of_week.strftime
    @endWeek = Date.today.at_beginning_of_week.advance(:days => 6)
    @nextWeek = Date.today.at_beginning_of_week.advance(:days => 7) #not formatted
    @endNextWeek = @nextWeek.advance(:days => 6)
  end

  def new
    @course = Course.new
  end

  def edit
    @course = Course.find_by_id(params[:id])
  end

  def create
    params[:class][:user_id] = @current_user.id
    @course = Course.create!(params[:class])
    redirect_to home_path
  end

  def update
    @course = Course.find_by_id(params[:id])
    @course.update_attributes!(params[:class])
    redirect_to course_path(params[:id])
  end

  def destroy
    @course = Course.find_by_id(params[:id])
    @course.destroy
    redirect_to home_path
  end

=begin
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :dueDate, :priority)
    end
=end

end

project/app/controllers/o_users_controller.rb
class OUsersController < ApplicationController
    skip_before_action :set_current_user, only:[:create, :validate, :signup]
  def new
  end
  def create
    #raise @user.inspect
    @user = OUser.create!(params[:user])
    session[:user_id] = @user.id
    redirect_to home_path
  end
  def show
    @user = User.find(params[:id])
  end
  def validate
    if !params.has_key?("user") #guest
        @user = OUser.create!(:name => "Guest")
        session[:user_id] = @user.id
        redirect_to home_path
    else
        @user = OUser.find_by email: params[:user][:email]
        if @user == nil
            redirect_to signup_path
        else #validate
            password = @user.password
            if params[:user][:password] == password
                session[:user_id] = @user.id
                redirect_to home_path
            else
                flash[:warning] = "Please try again"
                redirect_to :back
            end
        end
    end
    def signup
      @date = Date.today.strftime("%B %d, %Y")
    end
end
end

project/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :set_current_user #for first time login

  def create
    auth = request.env["omniauth.auth"]
    user = User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to '/home'
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end

  def failure
    redirect_to root_path
  end
end

project/app/controllers/static_controller.rb
class StaticController < ApplicationController
    skip_before_action :set_current_user, only:[:welcome, :about] #avoid redirect loop

    def home
        @classes = Course.find(:all, :conditions =>{:user_id => @current_user.id})
        @week = Date.today.at_beginning_of_week.strftime("%B %d, %Y")
        @endWeek = Date.today.at_beginning_of_week.advance(:days => 6)
        @date = Date.today.strftime("%B %d, %Y")
    end
    def welcome
        @date = Date.today.strftime("%B %d, %Y")
    end
    def about
        @current_user = OUser.find_by_id(session[:user_id])
        @date = Date.today.strftime("%B %d, %Y")
    end
end

project/app/controllers/users_controller.rb
class UsersController < ActionController::Base
    def oauth_failure
        redirect_to root_path
    end
end

project/app/helpers/application_helper.rb
module ApplicationHelper
end

project/app/helpers/o_users_helper.rb
module OUsersHelper
end

project/app/helpers/static_helper.rb
module StaticHelper
end

project/app/helpers/student_classes_helper.rb
module StudentClassesHelper
end

project/app/views/assignments/edit.html.haml
%h1 Edit Assignment

/ %form{:role => "form-center", :action => 'update', :method => "put", :class => "form-horizontal", :id => "aForm"}
= form_tag(course_assignment_path, method: "put", :class => "form-horizontal", :id => "aForm") do
    %div{:class => "form-group"}
        -if flash[:notice]
            %label{:class => "message col-sm-2 control-label", :id => "notice"}= flash[:notice]
        -elsif flash[:warning]
            %label{:class => "message col-sm-2 control-label", :id => "warning"}= flash[:warning]
    %div{:class => "form-group"}
        %label{:for => "inputAssignmentName", :class => "col-sm-2 control-label"}Assignment Name
        %div{:class => "col-sm-4"}
            %input{:type => "text", :class => "form-control", :id => "inputAssignmentName", :name => "assignment[name]", :value => @assignment.name}
    %div{:class => "form-group"}
        %label{:for => "inputDueDate", :class => "col-sm-2 control-label"}Due Date
        %div{:class => "col-sm-4"}
            /value acts like the placeholder
            %input{:type => "date", :class => "form-control", :id => "inputDueDate", :name => "assignment[dueDate]", :value => @assignment.dueDate}
    %div{:class => "form-group"}
        %label{:for => "inputDescription", :class => "col-sm-2 control-label"}Description
        %div{:class => "col-sm-4", :id => "inputDescription"}
            %textarea{:class => "form-control", :name => "assignment[description]"}#{@assignment.description}
    %div{:class => "form-group"}
        %div{:class => "col-sm-offset-2 col-sm-10"}
            %button{:type => "submit", :class => "btn btn-default"}Save

project/app/views/assignments/new.html.haml
%h1 Create Assignment
%form{:role => "form-center", :action => course_assignments_path, :method => "post", :class => "form-horizontal", :id => "aForm"}
    %div{:class => "form-group"}
        -if flash[:notice]
            %label{:class => "message col-sm-2 control-label", :id => "notice"}= flash[:notice]
        -elsif flash[:warning]
            %label{:class => "message col-sm-2 control-label", :id => "warning"}= flash[:warning]
    %div{:class => "form-group"}
        %label{:for => "inputAssignmentName", :class => "col-sm-2 control-label"}Assignment Name
        %div{:class => "col-sm-4"}
            %input{:type => "text", :class => "form-control", :id => "inputAssignmentName", :name => "assignment[name]"}
    %div{:class => "form-group"}
        %label{:for => "inputDueDate", :class => "col-sm-2 control-label"}Due Date
        %div{:class => "col-sm-4"}
            %input{:type => "date", :class => "form-control", :id => "inputDueDate", :name => "assignment[dueDate]"}
    %div{:class => "form-group"}
        %label{:for => "inputDescription", :class => "col-sm-2 control-label"}Description
        %div{:class => "col-sm-4", :id => "inputDescription"}
            %textarea{:class => "form-control", :name => "assignment[description"}
    %div{:class => "form-group"}
        %div{:class => "col-sm-offset-2 col-sm-10"}
            %button{:type => "submit", :class => "btn btn-default"}Save

project/app/views/assignments/show.html.haml
%h1 #{@assignment.name}

project/app/views/courses/create.html.haml
%Hi

project/app/views/courses/edit.html.haml
%h1 Edit Class
= form_tag(course_path(:id => params[:id]), method: "put", :class => "form-horizontal", :id => "aForm") do
    %div{:class => "form-group"}
        %label{:for => "inputClassName", :class => "col-sm-2 control-label"}Class Name
        %div{:class => "col-sm-4"}
            %input{:type => "text", :class => "form-control", :id => "inputClassName", :name =>"class[name]", :value => "#{@course.name}"}
    %div{:class =>"form-group"}
        %div{:class => "col-sm-offset-2 col-sm-10"}
            %button{:type => "submit", :class => "btn btn-default"}Save

project/app/views/courses/new.html.haml
%h1 Add A Class
%form{:role => "form-center", :action => courses_path, :method => "post", :class => "form-horizontal"}
    %div{:class => "form-group"}
        %label{:for => "inputClassName", :class => "col-sm-2 control-label"}Class Name
        %div{:class => "col-sm-4"}
            %input{:type => "text", :class => "form-control", :id => "inputClassName", :name =>"class[name]"}
    %div{:class =>"form-group"}
        %div{:class => "col-sm-offset-2 col-sm-10"}
            %button{:type => "submit", :class => "btn btn-default"}Save

project/app/views/courses/show.html.haml
%div{:class => "container-fluid"}
    %div{:class => "row"}
        %div{:class => "col-md-2"}
            %h3 Navigation
            %ol{:class => "nav nav-pills nav-stacked"}
                %li{:class => "text-left"}= link_to "Add Assignment", new_course_assignment_path(@id)
                %li{:class => "text-left"}=link_to "Edit Class", edit_course_path(@id)
                %li{:class => "text-left"}= link_to "Delete Class", course_path(params[:id]), :method => :delete, :confirm => 'Are you sure?'
                / %li{:class => "text-left"}=link_to "Late Assignments", late_path(params[:id]), :method => "get"
                / %li{:class => "text-left"}=link_to "Past Assignments", past_path(params[:id]), :method => "get"
        %div{:class => "col-md-10"}
            %h3 Upcoming Deadlines for #{@course.name}
            //section for this week, next week, later
            %div
                %div.padding
                %h4.blue This Week
                //for all of the assignments check if their date is < or end of week, if it is, put it
                %table{:class => "table table-striped"}
                    %tbody
                        -if @assignments.blank?
                            %tr
                                %td.format Nothing yet! Go read or something.
                        -else
                            -counter = 0
                            -@assignments.each do |assignment|
                                -if Date.parse(assignment.dueDate) <= @endWeek
                                    %tr
                                        %td.name.set.format #{assignment.name}
                                        %td.format Due on #{Date.parse(assignment.dueDate).strftime("%B %d, %Y")}
                                    -counter = counter + 1
                            -if counter ==0
                                %td.format Nothing yet! Go read or something.
            %div
                %div.padding
                %h4.blue Next Week
                %table{:class => "table table-striped"}
                    %tbody
                        -if @assignments.blank?
                            %tr
                                %td.format Nothing yet! Go read or something.
                        -else
                            -counter = 0
                            -@assignments.each do |assignment|
                                -aDueDate = Date.parse(assignment.dueDate)
                                -if aDueDate >= @nextWeek and aDueDate <= @endNextWeek
                                    %tr
                                        %td.format.name.set #{assignment.name}
                                        %td.format Due on #{Date.parse(assignment.dueDate).strftime("%B %d, %Y")}
                                    -counter = counter + 1
                            -if counter == 0
                                %td.format Nothing yet! Go read or something.
                //if date is after endWeek and before endNextWeek
    %div{:class => "row"}
        %div{:class => "col-md-offset-2 col-md-10"}
            %h3 All Assignments
            %table{:class => "table table-striped"}
                %tbody
                    -if @assignments.blank?
                        %tr
                            %td No assignments added yet
                    -else
                        - @assignments.each do |assignment|
                            %tr
                                %td.format.name.set #{assignment.name}
                                %td.format #{assignment.description}
                                / %td.format.button
                                /     = button_to "Done", done_path(:id =>assignment.id, :course_id => params[:id]), :method => "get", :class => "btn btn-default "
                                %td.format.button{:valign => "middle"}
                                    = button_to 'Edit', edit_course_assignment_path(:course_id => params[:id],:id => assignment.id ), :method => "get", :class => "btn btn-default"
                                %td.format.button
                                    = button_to 'Delete', course_assignment_path(params[:id],assignment.id), :method => :delete, :confirm => 'Are you sure?', :class => "btn btn-default"

project/app/views/layouts/application.html.haml
!!! 5
%html
    %head
        %title
        = stylesheet_link_tag 'application'
        = javascript_include_tag 'application'
        = csrf_meta_tags
        %body
        = render :partial=>'session/nav'
        = yield

project/app/views/o_users/signup.html.haml
%h1 First time?  Sign up here!
= form_tag(o_users_path, method: "post", :class => "form-horizontal", :id => "aForm") do
    %div{:class => "form-group"}
        -if flash[:notice]
            %label{:class => "message col-sm-2 control-label", :id => "notice"}= flash[:notice]
        -elsif flash[:warning]
            %label{:class => "message col-sm-2 control-label", :id => "warning"}= flash[:warning]
    %div{:class => "form-group"}
        %label{:class => "col-sm-2 control-label"}Name
        %div{:class => "col-sm-4"}
            %input{:type => "text", :class => "form-control",  :name => "user[name]"}
    %div{:class => "form-group"}
        %label{:class => "col-sm-2 control-label"}Email
        %div{:class => "col-sm-4"}
            %input{:type => "email", :class => "form-control",  :name => "user[email]"}
    %div{:class => "form-group"}
        %label{:class => "col-sm-2 control-label"}Password
        %div{:class => "col-sm-4"}
            %input{:type => "password", :class => "form-control", :name => "user[password]"}
    %div{:class => "form-group"}
        %div{:class => "col-sm-offset-2 col-sm-10"}
            %button{:type => "submit", :class => "btn btn-default"}Save

project/app/views/session/_nav.html.haml
%nav{:class => "navbar navbar-inverse", :role => "navigation"}
    %div{:class => "navbar-header"}
        %button{:type => "button", :class =>"navbar-toggle", "data-toggle" => "collapse", "data-target" => "#bs-example-navbar-collapse-1"}
            %span{:class => "sr-only"} Toggle navigation
            %span{:class => "icon-bar"}
            %span{:class => "icon-bar"}
            %span{:class => "icon-bar"}
        %div{:class=> "brand"}Enana
    %div{:class => "collapse navbar-collapse", :id =>"bs-example-navbar-collapse-1"}
        %ul{:class => "nav navbar-nav"}
            %li= link_to 'About', '/about'
            -if @current_user
                %li= link_to 'Dashboard', '/home'
                %li= link_to 'Logout', logout_path
            -else
                %li= link_to 'Login', root_path
        -if @current_user
            %p{:class => "navbar-text navbar-right"}Welcome, #{@current_user.name}!  Today is #{@date}
        -else
            %p{:class => "navbar-text navbar-right"}Hello stranger.  Today is #{@date}